In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import numpy as np

warnings.filterwarnings('ignore')
plt.rc('font',family='Batang')
plt.rcParams["figure.figsize"] = (10,10)

In [3]:
buy_weather_total = pd.read_csv("../활용 데이터셋/buy_weather_total.csv", encoding ='cp949', parse_dates=["일시"])

In [4]:
buy_weather_total

,sm_cat,일시,qty,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),평균 풍속(m/s),평균 상대습도(%),일 미세먼지 농도(㎍/㎥),불쾌지수,열지수,체감온도
0,가스온수기,2018-01-13,1,-3.685828,-8.640719,2.032535,0.027833,1.581162,69.144681,31.038462,30.903721,17.634558,-2.978124
1,가열식 가습기,2018-01-13,9,-3.685828,-8.640719,2.032535,0.027833,1.581162,69.144681,31.038462,30.903721,17.634558,-2.978124
2,공기정화 용품,2018-01-13,61,-3.685828,-8.640719,2.032535,0.027833,1.581162,69.144681,31.038462,30.903721,17.634558,-2.978124
3,공기청정기,2018-01-13,32,-3.685828,-8.640719,2.032535,0.027833,1.581162,69.144681,31.038462,30.903721,17.634558,-2.978124
4,난방용 열풍기,2018-01-13,2,-3.685828,-8.640719,2.032535,0.027833,1.581162,69.144681,31.038462,30.903721,17.634558,-2.978124
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23427,컨벡터,2019-09-13,1,21.101183,16.848317,26.746139,0.024606,1.687674,75.687234,14.478261,68.379877,66.715916,22.968683
23428,탁상/USB 선풍기,2019-09-13,3,21.101183,16.848317,26.746139,0.024606,1.687674,75.687234,14.478261,68.379877,66.715916,22.968683
23429,황토매트,2019-09-13,1,21.101183,16.848317,26.746139,0.024606,1.687674,75.687234,14.478261,68.379877,66.715916,22.968683
23430,휴대용 선풍기,2019-09-13,2,21.101183,16.848317,26.746139,0.024606,1.687674,75.687234,14.478261,68.379877,66.715916,22.968683
23431,히터,2019-09-13,6,21.101183,16.848317,26.746139,0.024606,1.687674,75.687234,14.478261,68.379877,66.715916,22.968683

## 온도 - 냉방

In [4]:
buy_weather_tpr = pd.read_csv("../활용 데이터셋/buy_weather_tpr.csv", encoding ='cp949', parse_dates=["일시"])

In [6]:
buy_weather_tpr

,sm_cat,일시,qty,평균기온(°C),최저기온(°C),최고기온(°C),불쾌지수,열지수,체감온도
0,멀티형 에어컨,2018-01-13,1,-3.685828,-8.640719,2.032535,30.903721,17.634558,-2.978124
1,멀티형 에어컨,2018-01-17,2,3.906139,1.162178,7.499802,40.264687,32.675597,4.970363
2,멀티형 에어컨,2018-01-29,4,-6.496414,-9.936183,-2.337972,31.110377,12.059606,-7.639590
3,멀티형 에어컨,2018-02-02,3,-2.955446,-8.610693,3.691881,35.298583,19.071703,-2.520548
4,멀티형 에어컨,2018-02-06,1,-8.508964,-12.716932,-4.041833,28.178318,8.075477,-9.794257
...,...,...,...,...,...,...,...,...,...
7250,업소용 선풍기,2019-08-22,18,25.098214,22.020990,29.666931,75.455659,74.633795,27.170333
7251,업소용 선풍기,2019-08-23,17,23.778585,19.844794,28.646365,72.516224,72.016976,25.828243
7252,업소용 선풍기,2019-08-24,2,22.137205,18.337992,26.999213,70.193037,68.768458,24.205349
7253,업소용 선풍기,2019-08-27,10,22.601584,20.336310,25.648611,71.911422,69.693647,24.666395
7254,업소용 선풍기,2019-09-07,1,24.907879,21.890381,28.249499,75.028004,74.256405,26.661456

## 온도 - 난방

In [5]:
buy_weather_tph = pd.read_csv("../활용 데이터셋/buy_weather_tph.csv", encoding ='cp949', parse_dates=["일시"])

In [8]:
buy_weather_tph

,sm_cat,일시,qty,평균기온(°C),최저기온(°C),최고기온(°C),불쾌지수,열지수,체감온도
0,가스온수기,2018-01-13,1,-3.685828,-8.640719,2.032535,30.903721,17.634558,-2.978124
1,가스온수기,2018-01-17,1,3.906139,1.162178,7.499802,40.264687,32.675597,4.970363
2,가스온수기,2018-01-19,1,0.716963,-3.344379,6.536884,39.199984,26.346149,1.513794
3,가스온수기,2018-01-29,2,-6.496414,-9.936183,-2.337972,31.110377,12.059606,-7.639590
4,가스온수기,2018-02-02,1,-2.955446,-8.610693,3.691881,35.298583,19.071703,-2.520548
...,...,...,...,...,...,...,...,...,...
8069,히터,2019-08-23,10,23.778585,19.844794,28.646365,72.516224,72.016976,25.828243
8070,히터,2019-08-24,14,22.137205,18.337992,26.999213,70.193037,68.768458,24.205349
8071,히터,2019-08-27,11,22.601584,20.336310,25.648611,71.911422,69.693647,24.666395
8072,히터,2019-09-07,6,24.907879,21.890381,28.249499,75.028004,74.256405,26.661456
8073,히터,2019-09-13,6,21.101183,16.848317,26.746139,68.379877,66.715916,22.968683

## 습도

In [6]:
buy_weather_hm = pd.read_csv("../활용 데이터셋/buy_weather_hm.csv", encoding ='cp949', parse_dates=["일시"])

In [10]:
buy_weather_hm

,sm_cat,일시,qty,평균기온(°C),최저기온(°C),최고기온(°C),불쾌지수,열지수,체감온도
0,제습기,2018-01-13,9,-3.685828,-8.640719,2.032535,30.903721,17.634558,-2.978124
1,제습기,2018-01-17,21,3.906139,1.162178,7.499802,40.264687,32.675597,4.970363
2,제습기,2018-01-19,24,0.716963,-3.344379,6.536884,39.199984,26.346149,1.513794
3,제습기,2018-01-29,35,-6.496414,-9.936183,-2.337972,31.110377,12.059606,-7.639590
4,제습기,2018-02-02,8,-2.955446,-8.610693,3.691881,35.298583,19.071703,-2.520548
...,...,...,...,...,...,...,...,...,...
5340,에어워셔,2019-08-23,2,23.778585,19.844794,28.646365,72.516224,72.016976,25.828243
5341,에어워셔,2019-08-24,4,22.137205,18.337992,26.999213,70.193037,68.768458,24.205349
5342,에어워셔,2019-08-27,4,22.601584,20.336310,25.648611,71.911422,69.693647,24.666395
5343,에어워셔,2019-09-07,1,24.907879,21.890381,28.249499,75.028004,74.256405,26.661456
5344,에어워셔,2019-09-13,1,21.101183,16.848317,26.746139,68.379877,66.715916,22.968683

## 공기

In [7]:
buy_weather_ar = pd.read_csv("../활용 데이터셋/buy_weather_ar.csv", encoding ='cp949', parse_dates=["일시"])

In [12]:
buy_weather_ar

     sm_cat         일시  qty  일 미세먼지 농도(㎍/㎥)
0     공기청정기 2018-01-13   32       31.038462
1     공기청정기 2018-01-17  568       37.296296
2     공기청정기 2018-01-19  233       46.653846
3     공기청정기 2018-01-29  245       33.703704
4     공기청정기 2018-02-02  118       31.392857
...     ...        ...  ...             ...
1549   산림욕기 2019-06-26    1       24.291667
1550   산림욕기 2019-07-09    3       14.652174
1551   산림욕기 2019-07-11    1       10.235294
1552   산림욕기 2019-07-22    1       27.535714
1553   산림욕기 2019-08-05    1       33.333333

[1554 rows x 4 columns]

## 냉난방

In [8]:
buy_weather_tp = pd.read_csv("../활용 데이터셋/buy_weather_tp.csv", encoding ='cp949', parse_dates=["일시"])

In [14]:
buy_weather_tp

,sm_cat,일시,qty,평균기온(°C),최저기온(°C),최고기온(°C),불쾌지수,열지수,체감온도
0,벽걸이형 냉온풍기,2018-01-29,2,-6.496414,-9.936183,-2.337972,31.110377,12.059606,-7.639590
1,벽걸이형 냉온풍기,2018-03-07,2,4.769000,0.933200,8.830600,43.206644,34.376752,5.188178
2,벽걸이형 냉온풍기,2018-03-13,1,11.290514,2.889307,18.440198,53.437619,47.285438,12.057262
3,벽걸이형 냉온풍기,2018-03-27,2,12.200593,4.460672,19.939328,54.818346,49.086036,13.357434
4,벽걸이형 냉온풍기,2018-04-19,1,13.542490,4.642262,21.921230,56.837360,51.736872,14.829190
...,...,...,...,...,...,...,...,...,...
1199,스탠드형 냉온풍기,2019-08-23,9,23.778585,19.844794,28.646365,72.516224,72.016976,25.828243
1200,스탠드형 냉온풍기,2019-08-24,11,22.137205,18.337992,26.999213,70.193037,68.768458,24.205349
1201,스탠드형 냉온풍기,2019-08-27,16,22.601584,20.336310,25.648611,71.911422,69.693647,24.666395
1202,스탠드형 냉온풍기,2019-09-07,7,24.907879,21.890381,28.249499,75.028004,74.256405,26.661456
1203,스탠드형 냉온풍기,2019-09-13,2,21.101183,16.848317,26.746139,68.379877,66.715916,22.968683

## Random Forest

### 평가기준

In [15]:
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import mean_absolute_error

In [16]:
def MAPE(y_test, y_pred):
    return np.mean(np.abs((y_test - y_pred) / y_test)) * 100 

def MPE(y_test, y_pred): 
    return np.mean((y_test - y_pred) / y_test) * 100

def get_rmse(model):
    global mpe
    global mape
    pred = model.predict(X_test)
    mse = mean_squared_error(y_test , pred)
    rmse = np.sqrt(mse)
    mpe = MPE(y_test,pred)
    mape = MAPE(y_test,pred)
    mae = mean_absolute_error(y_test, pred)

    r2 = r2_score(y_test, pred)
    
    print('{0} 로그 변환된 RMSE: {1}'.format(model.__class__.__name__,np.round(rmse, 3)))
    print('{0} 로그 변환된 MSE: {1}'.format(model.__class__.__name__,np.round(mse, 3)))
    print('{0} 로그 변환된 MAE: {1}'.format(model.__class__.__name__,np.round(mae, 3)))
    print('{0} 로그 변환된 MAPE: {1}'.format(model.__class__.__name__,np.round(mape, 3)))
    print('{0} 로그 변환된 MPE: {1}'.format(model.__class__.__name__,np.round(mpe, 3)))
    print('r2-score : {0:.3f}'.format(r2))
    return rmse,mse,mae,mape,mpe,r2

In [17]:
def get_rmses(model):
#     rmses=[]
    rmse,mse,mae,mape,mpe,r2 = get_rmse(model)
#     rmses.append(rmse)
#   tpr_eval_test= tpr_eval_test.append({'sm_cat': cg_,'model':model,'MSE': mse, 'RMSE': rmse, 'MAE':mae, 'MAPE':mape,
#                                      'MPE':mpe,'R2-score':r2}, ignore_index=True)
        
    return rmse,mse,mae,mape,mpe,r2

### 함수

In [18]:
from sklearn.model_selection import GridSearchCV

def print_best_params(model, params):
    grid_model = GridSearchCV(model, param_grid=params, 
                              scoring='neg_mean_squared_error', cv=5)
    grid_model.fit(X_train,y_train)
    rmse = np.sqrt(-1* grid_model.best_score_)
    print('{0} 5 CV 시 최적 평균 RMSE 값: {1}, 최적 alpha:{2}'.format(model.__class__.__name__,
                                        np.round(rmse, 4), grid_model.best_params_))
    return grid_model.best_estimator_, grid_model.best_params_

In [19]:
from sklearn.model_selection import train_test_split

# 인자로 입력받은 DataFrame을 복사 한 뒤 Time 컬럼만 삭제하고 복사된 DataFrame 반환
def get_preprocessed_df(df=None):
    df_copy = df.copy()
    df_copy.drop(['sm_cat','일시'], axis=1, inplace=True)
    return df_copy

In [20]:
# 사전 데이터 가공 후 학습과 테스트 데이터 세트를 반환하는 함수.
def get_train_test_dataset(df=None):
    df = get_preprocessed_df(df)
    
    features_index = df.dtypes[df.dtypes != 'object'].index
    skew_features = df[features_index].apply(lambda x : skew(x))
    skew_features_top = skew_features[skew_features > 1]
    df[skew_features_top.index] = np.log1p(df[skew_features_top.index])
    
    X_features = df.drop('qty',axis=1, inplace=False)
    y_target = df['qty']
    X_train, X_test, y_train, y_test = train_test_split(X_features, y_target, test_size=0.2, random_state=156)
    
    return X_features,y_target,X_train, X_test, y_train, y_test

In [21]:
ar_eval_test_rf = pd.DataFrame(columns=['sm_cat','model','max_depth','min_samples_leaf','min_samples_split','MSE','RMSE','MAE','MAPE',
                                      'MPE','R2-score'])

In [22]:
hm_eval_test_rf = pd.DataFrame(columns=['sm_cat','model','max_depth','min_samples_leaf','min_samples_split','MSE','RMSE','MAE','MAPE',
                                      'MPE','R2-score'])

In [23]:
tpr_eval_test_rf = pd.DataFrame(columns=['sm_cat','model','max_depth','min_samples_leaf','min_samples_split','MSE','RMSE','MAE','MAPE',
                                      'MPE','R2-score'])

In [24]:
tph_eval_test_rf = pd.DataFrame(columns=['sm_cat','model','max_depth','min_samples_leaf','min_samples_split','MSE','RMSE','MAE','MAPE',
                                      'MPE','R2-score'])

In [25]:
tp_eval_test_rf = pd.DataFrame(columns=['sm_cat','model','max_depth','min_samples_leaf','min_samples_split','MSE','RMSE','MAE','MAPE',
                                      'MPE','R2-score'])

## 냉난방

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from scipy.stats import skew


for cg_ in ['벽걸이형 냉온풍기','스탠드형 냉온풍기']:
    buy_weather_tp_cg = buy_weather_tp[buy_weather_tp['sm_cat'] == cg_]
    
    X_features,y_target,X_train, X_test, y_train, y_test = get_train_test_dataset(buy_weather_tp_cg)
    
    rf_params = {'max_depth': [6,8,10,12],'min_samples_leaf': [3,5,7,10],'min_samples_split': [2,3,5,10]}
    rf_reg = RandomForestRegressor()
    best_rf, best_params_ = print_best_params(rf_reg, rf_params)
    
    max_depth= best_params_['max_depth']
    min_samples_leaf= best_params_['min_samples_leaf']
    min_samples_split= best_params_['min_samples_split'] 
    
    rf_reg = RandomForestRegressor(max_depth=max_depth, min_samples_leaf= min_samples_leaf, min_samples_split= min_samples_split)
    rf_reg.fit(X_train, y_train)
    rmse,mse,mae,mape,mpe,r2=get_rmse(rf_reg)
    
    tp_eval_test_rf= tp_eval_test_rf.append({'sm_cat': cg_,'model':'RF','MSE': mse, 'RMSE': rmse, 'MAE':mae, 'MAPE':mape,
                                     'MPE':mpe,'R2-score':r2,'max_depth':max_depth, 'min_samples_leaf':min_samples_leaf, 'min_samples_split':min_samples_split}, ignore_index=True)
    print(cg_,'\n')

RandomForestRegressor 5 CV 시 최적 평균 RMSE 값: 0.5755, 최적 alpha:{'max_depth': 6, 'min_samples_leaf': 5, 'min_samples_split': 10}
RandomForestRegressor 로그 변환된 RMSE: 0.523
RandomForestRegressor 로그 변환된 MSE: 0.274
RandomForestRegressor 로그 변환된 MAE: 0.421
RandomForestRegressor 로그 변환된 MAPE: 39.383
RandomForestRegressor 로그 변환된 MPE: -15.595
r2-score : -0.100
벽걸이형 냉온풍기

RandomForestRegressor 5 CV 시 최적 평균 RMSE 값: 0.6434, 최적 alpha:{'max_depth': 6, 'min_samples_leaf': 5, 'min_samples_split': 10}
RandomForestRegressor 로그 변환된 RMSE: 0.671
RandomForestRegressor 로그 변환된 MSE: 0.451
RandomForestRegressor 로그 변환된 MAE: 0.548
RandomForestRegressor 로그 변환된 MAPE: 29.639
RandomForestRegressor 로그 변환된 MPE: -14.551
r2-score : 0.140
스탠드형 냉온풍기

In [28]:
tp_eval_test_rf

,sm_cat,model,max_depth,min_samples_leaf,min_samples_split,MSE,RMSE,MAE,MAPE,MPE,R2-score
0,벽걸이형 냉온풍기,RF,6,5,10,0.273763,0.523224,0.421359,39.382553,-15.594710,-0.099752
1,스탠드형 냉온풍기,RF,6,5,10,0.450511,0.671201,0.548249,29.639232,-14.551056,0.139792

In [29]:
tp_eval_test_rf.to_csv('../활용 데이터셋/tp_eval_rf.csv', encoding='cp949',index=False)

## 공기

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from scipy.stats import skew


for cg_ in ['공기청정기','공기정화 용품','산림욕기']:
    buy_weather_ar_cg = buy_weather_ar[buy_weather_ar['sm_cat'] == cg_]
    
    X_features,y_target,X_train, X_test, y_train, y_test = get_train_test_dataset(buy_weather_ar_cg)
    
    rf_params = {'max_depth': [6,8,10,12],'min_samples_leaf': [3,5,7,10],'min_samples_split': [2,3,5,10]}
    rf_reg = RandomForestRegressor()
    best_rf, best_params_ = print_best_params(rf_reg, rf_params)
    
    max_depth= best_params_['max_depth']
    min_samples_leaf= best_params_['min_samples_leaf']
    min_samples_split= best_params_['min_samples_split'] 
    
    rf_reg = RandomForestRegressor(max_depth=max_depth, min_samples_leaf= min_samples_leaf, min_samples_split= min_samples_split)
    rf_reg.fit(X_train, y_train)
    rmse,mse,mae,mape,mpe,r2=get_rmse(rf_reg)
    
    ar_eval_test_rf= ar_eval_test_rf.append({'sm_cat': cg_,'model':'RF','MSE': mse, 'RMSE': rmse, 'MAE':mae, 'MAPE':mape,
                                     'MPE':mpe,'R2-score':r2,'max_depth':max_depth, 'min_samples_leaf':min_samples_leaf, 'min_samples_split':min_samples_split}, ignore_index=True)
    print(cg_,'\n')

In [ ]:
ar_eval_test_rf

## 습도

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from scipy.stats import skew


for cg_ in ['제습기','초음파식 가습기','자연식 가습기','복합식 가습기','신발건조기','의류건조기','가열식 가습기','에어워셔']:
    buy_weather_hm_cg = buy_weather_hm[buy_weather_hm['sm_cat'] == cg_]
    
    rf_params = {'max_depth': [6,8,10,12],'min_samples_leaf': [3,5,7,10],'min_samples_split': [2,3,5,10]}
    rf_reg = RandomForestRegressor()
    best_rf, best_params_ = print_best_params(rf_reg, rf_params)
    
    max_depth= best_params_['max_depth']
    min_samples_leaf= best_params_['min_samples_leaf']
    min_samples_split= best_params_['min_samples_split'] 
    
    rf_reg = RandomForestRegressor(max_depth=max_depth, min_samples_leaf= min_samples_leaf, min_samples_split= min_samples_split)
    rf_reg.fit(X_train, y_train)
    rmse,mse,mae,mape,mpe,r2=get_rmse(rf_reg)
    
    hm_eval_test_rf= hm_eval_test_rf.append({'sm_cat': cg_,'model':'RF','MSE': mse, 'RMSE': rmse, 'MAE':mae, 'MAPE':mape,
                                     'MPE':mpe,'R2-score':r2,'max_depth':max_depth, 'min_samples_leaf':min_samples_leaf, 'min_samples_split':min_samples_split}, ignore_index=True)
    print(cg_,'\n')

In [ ]:
hm_eval_test_rf

## 온도 - 냉방

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from scipy.stats import skew


for cg_ in ['멀티형 에어컨', '벽걸이 에어컨', '벽걸이형 선풍기', '스탠드형 에어컨', '에어컨 리모컨', '탁상/USB 선풍기',
       '휴대용 선풍기', '냉풍기', '이동형 에어컨', '중대형 에어컨', '천장형 에어컨', '에어커튼', '업소용 선풍기']:
    buy_weather_tpr_cg = buy_weather_tpr[buy_weather_tpr['sm_cat'] == cg_]
    
    X_features,y_target,X_train, X_test, y_train, y_test = get_train_test_dataset(buy_weather_tpr_cg)
  
    rf_params = {'max_depth': [6,8,10,12],'min_samples_leaf': [3,5,7,10],'min_samples_split': [2,3,5,10]}
    rf_reg = RandomForestRegressor()
    best_rf, best_params_ = print_best_params(rf_reg, rf_params)
    
    max_depth= best_params_['max_depth']
    min_samples_leaf= best_params_['min_samples_leaf']
    min_samples_split= best_params_['min_samples_split'] 
    
    rf_reg = RandomForestRegressor(max_depth=max_depth, min_samples_leaf= min_samples_leaf, min_samples_split= min_samples_split)
    rf_reg.fit(X_train, y_train)
    rmse,mse,mae,mape,mpe,r2=get_rmse(rf_reg)
    
    tpr_eval_test_rf= tpr_eval_test_rf.append({'sm_cat': cg_,'model':'RF','MSE': mse, 'RMSE': rmse, 'MAE':mae, 'MAPE':mape,
                                     'MPE':mpe,'R2-score':r2,'max_depth':max_depth, 'min_samples_leaf':min_samples_leaf, 'min_samples_split':min_samples_split}, ignore_index=True)
    print(cg_,'\n')

In [ ]:
tpr_eval_test_rf

## 온도 - 난방

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from scipy.stats import skew


for cg_ in ['가스온수기', '난방용 열풍기', '돈풍기', '라디에이터', '보일러', '온수매트', '온열매트',
       '온풍기', '전기온수기', '전기장판', '카페트매트', '컨벡터', '황토매트', '히터']:
    buy_weather_tph_cg = buy_weather_tph[buy_weather_tph['sm_cat'] == cg_]
    
    X_features,y_target,X_train, X_test, y_train, y_test = get_train_test_dataset(buy_weather_tph_cg)
    
    rf_params = {'max_depth': [6,8,10,12],'min_samples_leaf': [3,5,7,10],'min_samples_split': [2,3,5,10]}
    rf_reg = RandomForestRegressor()
    best_rf, best_params_ = print_best_params(rf_reg, rf_params)
    
    max_depth= best_params_['max_depth']
    min_samples_leaf= best_params_['min_samples_leaf']
    min_samples_split= best_params_['min_samples_split'] 
    
    rf_reg = RandomForestRegressor(max_depth=max_depth, min_samples_leaf= min_samples_leaf, min_samples_split= min_samples_split)
    rf_reg.fit(X_train, y_train)
    rmse,mse,mae,mape,mpe,r2=get_rmse(rf_reg)
    
    tph_eval_test_rf= tph_eval_test_rf.append({'sm_cat': cg_,'model':'RF','MSE': mse, 'RMSE': rmse, 'MAE':mae, 'MAPE':mape,
                                     'MPE':mpe,'R2-score':r2,'max_depth':max_depth, 'min_samples_leaf':min_samples_leaf, 'min_samples_split':min_samples_split}, ignore_index=True)
    print(cg_,'\n')

In [ ]:
tph_eval_test_rf

In [ ]:
tpr_eval_test_rf.to_csv('../활용 데이터셋/tpr_eval_rf.csv', encoding='cp949',index=False)
tph_eval_test_rf.to_csv('../활용 데이터셋/tph_eval_rf.csv', encoding='cp949',index=False)
hm_eval_test_rf.to_csv('../활용 데이터셋/hm_eval_rf.csv', encoding='cp949',index=False)
ar_eval_test_rf.to_csv('../활용 데이터셋/ar_eval_rf.csv', encoding='cp949',index=False)